config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :contacts
  resources :models
  resources :profiles
  resources :blogs
  resources :blogs
  devise_for :users, controllers: {
    registrations: "registrations"
  }
  resources :favorites, only: [:create, :destroy, :index]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  mount_uploader :image,ImageUploader
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  validates :content, presence: true
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  def index
    @blogs = Blog.all
  end
  def show
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end
  def new
    @blog = current_user.blogs.build
  end
  def edit
  end
  def create
    @blog = current_user.blogs.build(blog_params)
    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
  def set_blog
     @blog = Blog.find(params[:id])
  end
  def blog_params
      params.require(:blog).permit(:content, :image, :user_id)
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>
      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, class:"form-control" %>
  </div>
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, class:"btn btn-primary" %>
  </div>
  <div class="field">
    <%= form.hidden_field :user_id %>
  </div>
  <div class="actions">
    <p class="btn btn-primary" ><%= form.submit %></p>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>
<%= render 'form', blog: @blog %>
<%= link_to 'Back', blogs_path, class:"btn btn-primary" %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Favorites', favorites_path, class:"btn btn-info" %>
<div class="center">
    <h1>Posts</h1

    
</div>
<%= link_to 'New Post', new_blog_path, class:"btn btn-info" %>
                        <% @blogs.each do |blog| %>
                            <div class="container">
                            <% if blog.user.profile == nil %>
                            <p><%= image_tag 'pro1.jpg', class:"rounded-circle1" %>
                            <%= blog.user.name %>
                        <% else %>
                            <% if blog.user.profile.image? %>
                            <p><%= image_tag blog.user.profile.image.url, class:"rounded-circle1" %>
                            <%= blog.user.email %>
                            </p>
                            <% end %>
                        <% end %>
                        
                        <% if blog.image.url %>
                        <%= image_tag blog.image.url, class:"image2" %>
                        <% end %>
                        <p><%= blog.content %></p>
                        <%= link_to 'Show', blog, class:"btn btn-primary" %>
                       
                        <% if blog.user == current_user %>
                        <%= link_to 'Edit', edit_blog_path(blog), class:"btn btn-primary"%>
                        <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-primary" %>
                        <% end %>
                        
                   
        </div>
        <% end %>
    

app/views/blogs/new.html.erb
<h1>New Blog</h1>
<%= render 'form', blog: @blog %>
<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <%= @blog.content %>
</p>
<p>
  <% if @blog.image.url %>
      <%= image_tag @blog.image.url, class:"image" %>
  <% end %>
</p>
<p>
  <%=@blog.user.name %>
</p>
<% unless @blog.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'Cancel favorite', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'Make it a favorite', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>
<%= link_to 'Back', blogs_path, class: "btn btn-primary"  %>